; PlatformIO Project Configuration File
; Сделано для Ёрадио nva_lw

[env:yoradio-esp32s3]

;platform = espressif32
platform = espressif32 @ 6.9.0
board = ESP32-S3-DevKitC-1
framework = arduino

board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags = -DBOARD_HAS_PSRAM

monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv

upload_protocol = esptool

lib_deps =
    adafruit/Adafruit GFX Library
    ;adafruit/Adafruit SSD1306                  ; тут освобождаем от ';' нужный вам дисплей, ненужный наоборот
    ;adafruit/Adafruit SH110X
    adafruit/Adafruit ILI9341
    ;adafruit/Adafruit ST7735 and ST7789 Library ; какого то хрена не хочет ее брать из библов Ардуино, 
                                                 ; скорее всего пугает название для 2-х дисплеев
    crankyoldgit/IRremoteESP8266

